// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3DuNlwHSqRS7xPQd4e7-LePer0UWFd6U',
    appId: '1:689851407543:web:13efd5075cf1ccd188c132',
    messagingSenderId: '689851407543',
    projectId: 'babybear-d6bcb',
    authDomain: 'babybear-d6bcb.firebaseapp.com',
    databaseURL: 'https://babybear-d6bcb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babybear-d6bcb.appspot.com',
    measurementId: 'G-7NLHMJ3WT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNfnkEcowJ4LiRwr6Cq3iBH0C1GbM2L_Y',
    appId: '1:689851407543:android:65840309935942eb88c132',
    messagingSenderId: '689851407543',
    projectId: 'babybear-d6bcb',
    databaseURL: 'https://babybear-d6bcb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babybear-d6bcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLEESpcE7m8Tc5MhiId-X5YdJiAN37Gtw',
    appId: '1:689851407543:ios:9d94d732577a065388c132',
    messagingSenderId: '689851407543',
    projectId: 'babybear-d6bcb',
    databaseURL: 'https://babybear-d6bcb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babybear-d6bcb.appspot.com',
    iosBundleId: 'com.example.babybeargamma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLEESpcE7m8Tc5MhiId-X5YdJiAN37Gtw',
    appId: '1:689851407543:ios:ad0e0362b693e40488c132',
    messagingSenderId: '689851407543',
    projectId: 'babybear-d6bcb',
    databaseURL: 'https://babybear-d6bcb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babybear-d6bcb.appspot.com',
    iosBundleId: 'com.example.babybeargamma.RunnerTests',
  );
}
